CREATE TABLE PROFILE (
   ID INTEGER PRIMARY KEY     NOT NULL,
   DESCRIPTION           TEXT    NOT NULL,
   TYPE            TEXT ,
   DIRECTION        TEXT,
   INTERVAL         INTEGER,
   STOP_CHECK           INTEGER,
   SHALLOW_WINDOW       INTEGER ,
   SHALLOW_DEPTH INTEGER ,
   DEEP_DEPTH INTEGER ,
   DEEP_WINDOW  INTEGER ,
   RAMP_TIME INTEGER,
   MAX_TIME INTEGER,
   BACKTRACK_TIMES INTEGER ,
   BACKTRACK_COUNT INTEGER,
   STALL_TIMEOUT INTEGER ,
   CTD_WRAPUP_TIME INTEGER,
   DPDT INTEGER
);

CREATE TABLE PATTERN_PROFILE(
   ID INTEGER PRIMARY KEY     NOT NULL,
   PROFILE_ID INTEGER
);

CREATE TABLE PATTERN(
   ID INTEGER PRIMARY KEY     NOT NULL,
   meta TEXT,
   start_dt NUMERIC,
   stop_dt NUMERIC,
   type INTEGER,
   status INTEGER,
   end INTEGER
);